### ISSUE TITLE
mindmap demo with InterSystems IRIS

### ISSUE THREAD

**Issue by dkutac** [yurimarx/global-mindmap#1]
Yuri, tried to install and run your project, but browser shoed just empty page when navigated to http://ipaddress:3000 page

here is part of docker-compose log
Step 4/6 : RUN npm install
 ---> Running in 24c582c5b830
**npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.**

added 1441 packages, and audited 1442 packages in 26s

176 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
**npm notice
npm notice New minor version of npm available! 8.5.0 -> 8.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
npm notice Run `npm install -g npm@8.6.0` to update!
npm notice**
Removing intermediate container 24c582c5b830
 ---> 798023960af1
Step 5/6 : EXPOSE 3000
 ---> Running in 92b4e328e9c3
Removing intermediate container 92b4e328e9c3
 ---> 68b0a0f3c2bc
Step 6/6 : CMD [ "npm", "start" ]
 ---> Running in 1078ee759d66
Removing intermediate container 1078ee759d66
 ---> aa271a0b7849
Successfully built aa271a0b7849
Successfully tagged global-mindmap_frontend:latest
Creating global-mindmap_iris_1 ... done
Creating frontend              ... done
root@u4docker:/home/kutac/global-mindmap# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS                     PORTS                                                                                                                                                          NAMES
e287781748e6   global-mindmap_iris       "/tini -- /iris-main"    3 minutes ago   Up 3 minutes (unhealthy)   0.0.0.0:1972->1972/tcp, :::1972->1972/tcp, 0.0.0.0:52773->52773/tcp, :::52773->52773/tcp, 2188/tcp, 0.0.0.0:53773->53773/tcp, :::53773->53773/tcp, 54773/tcp   global-mindmap_iris_1
1dfb0ea02000   global-mindmap_frontend   "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes               0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                                                      frontend

any idea?

**Comment by yurimarx** [comment]
try http://localhost:3000, not your ip address. Let me know if worked. If not, we can get meeting on discord to see the problem

**Comment by dkutac** [comment]
Well, I un a linux server, not desktop, so I can’t use localhost ip address

**Comment by yurimarx** [comment]
Do you have discord user on InterSystems Discord channel?

**Comment by dkutac** [comment]
Unfortunately not

**Comment by yurimarx** [comment]
I found the error and fixed on my source code. The code was localhost dependent, I fixed it. Please, do: 1 - git pull, 2 - docker build, 3 - docker up -d, 4 - http://yourip:3000. Thanks!

**Comment by dkutac** [comment]
Ok, thanks for hints. I’ll give it a try, but need to do other stuff now.

Dan

**Comment by yurimarx** [comment]
I found the error and fixed on my source code. The code was localhost dependent, I fixed it. Please, do: 1 - git pull, 2 - docker build, 3 - docker up -d, 4 - http://yourip:3000/. Thanks!
